//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kent.Boogaart.KBCsv.PerformanceTests.Utility {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DataResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DataResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kent.Boogaart.KBCsv.PerformanceTests.Utility.DataResources", typeof(DataResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;&quot;&quot;&quot;&quot;&quot;&quot;&quot;&quot;&quot;&quot;&quot;&quot;&quot;&quot;&quot;&quot;&quot;.
        /// </summary>
        internal static string CopiousEscapedDelimiters {
            get {
                return ResourceManager.GetString("CopiousEscapedDelimiters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to abc        ,              def,ghi            
        ///				abc				,							def,ghi						
        ///	 	   abc    	  ,  	     	   def,ghi.
        /// </summary>
        internal static string CopiousWhiteSpace {
            get {
                return ResourceManager.GetString("CopiousWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;She said &quot;&quot;hello&quot;&quot;&quot;,&quot;first,second,third&quot;,&quot;a value over
        ///two lines&quot;
        ///&quot;He said &quot;&quot;hi there&quot;&quot;&quot;,&quot;fourth,fifth,sixth&quot;,&quot;a value over
        ///three
        ///lines&quot;
        ///&quot;She said &quot;&quot;what&apos;s up?&quot;&quot;&quot;,&quot;seventh,eighth,ninth,tenth&quot;,&quot;a value
        ///over
        ///four
        ///lines&quot;.
        /// </summary>
        internal static string Delimited {
            get {
                return ResourceManager.GetString("Delimited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kent,Boogaart,33,Sidcup
        ///Belinda,Boogaart,34,Sidcup
        ///Tempany,Boogaart,8,Sidcup.
        /// </summary>
        internal static string PlainData {
            get {
                return ResourceManager.GetString("PlainData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;1&quot;,563355,62701,0,1235000081,&quot;php,error,gd,image-processing&quot;,220,2,563372,67183,2,1235000501
        ///&quot;2&quot;,563355,62701,0,1235000081,&quot;php,error,gd,image-processing&quot;,220,2,563374,66554,0,1235000551
        ///&quot;3&quot;,563356,15842,10,1235000140,&quot;lisp,scheme,subjective,clojure&quot;,1047,16,563358,15842,3,1235000177
        ///&quot;4&quot;,563356,15842,10,1235000140,&quot;lisp,scheme,subjective,clojure&quot;,1047,16,563413,893,18,1235001545
        ///&quot;5&quot;,563356,15842,10,1235000140,&quot;lisp,scheme,subjective,clojure&quot;,1047,16,563454,11649,4,1235002457
        ///&quot;6&quot;,563356,15842,10,123500 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Stackoverflow {
            get {
                return ResourceManager.GetString("Stackoverflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;first&quot;,&quot;second&quot;,&quot;third fourth fifth&quot;
        ///&quot;1&quot;,&quot;2&quot;,&quot;3 4 5&quot;
        ///&quot;abc&quot;,&quot;def&quot;,&quot;ghijklmnoopqrstuvwxyz - 0123456789&quot;.
        /// </summary>
        internal static string UnnecessarilyDelimited {
            get {
                return ResourceManager.GetString("UnnecessarilyDelimited", resourceCulture);
            }
        }
    }
}
