// <auto-generated/>
using System;
using System.Reflection;
using System.Resources;

[assembly: AssemblyVersionAttribute("3.0.3.0")]
[assembly: AssemblyFileVersionAttribute("3.0.3.0")]
[assembly: AssemblyConfigurationAttribute("Release")]
[assembly: AssemblyCompanyAttribute("Kent Boogaart")]
[assembly: AssemblyProductAttribute("KBCsv")]
[assembly: AssemblyCopyrightAttribute("© Copyright. Kent Boogaart.")]
[assembly: AssemblyTrademarkAttribute("")]
[assembly: AssemblyCultureAttribute("")]
[assembly: CLSCompliantAttribute(true)]
[assembly: NeutralResourcesLanguageAttribute("en-US")]
[assembly: AssemblyInformationalVersionAttribute("3.0.3")]
